doc/notebooks/afq-object.ipynb
=> Added a notebook with some design discussion.

AFQ/version.py
Just a couple of missed changes I saw while looking over the code
=> shablona => pyAFQ

.gitignore, .travis.yml, AFQ/__init__.py, AFQ/api.py, AFQ/tests/test_api.py, doc/notebooks/afq-object.ipynb, setup.py
Also, gitignore file, some further module setup stuff.
Please don't merge yet!
=> WIP: Started to set up tests.

AFQ/dki.py
=> built a module to fit dki parameters and write out images

AFQ/dki.py, AFQ/tests/test_dki.py, bin/pyAFQ_dki
And changed the key-word args to make more sense. cc: @libbyhuber
=> DKI documentation

AFQ/_fixes.py, AFQ/api.py, AFQ/dki.py, AFQ/dti.py, AFQ/tests/test_dki.py, AFQ/tests/test_dti.py, AFQ/tests/test_scripts.py, AFQ/tests/utils.py, bin/pyAFQ_dki, bin/pyAFQ_dki_predict, bin/pyAFQ_dti, bin/pyAFQ_dti_predict
Check-list for things that I still need to do here:
=> DTI and model predictions

.travis.yml, AFQ/_fixes.py, AFQ/csd.py, AFQ/dki.py, AFQ/dti.py, AFQ/tests/test_csd.py, AFQ/tests/test_dti.py, AFQ/tests/test_tractography.py, AFQ/tractography.py, AFQ/utils/models.py, AFQ/utils/testing.py
First pass at tractography: this does deterministic tracking with CSD. Fitting the model and doing the tracking are separated into two different steps, and CSD parameters are stored as a nifti file.
=> Tractography

AFQ/dki.py, AFQ/registration.py, AFQ/tests/test_registration.py
But testing probably needs revision, since this takes a while...
=> Added some tools for registration. Started testing them.

AFQ/dki.py, AFQ/dti.py, AFQ/tests/test_scripts.py, AFQ/utils/models.py, bin/pyAFQ_dki, bin/pyAFQ_dki_predict, bin/pyAFQ_dti, bin/pyAFQ_dti_predict
=> NF: Add a b0_threshold parameter for model fitting.

.travis.yml, AFQ/api.py, AFQ/data.py, AFQ/dti.py, AFQ/segmentation.py, AFQ/tests/test_api.py, AFQ/tests/test_tractography.py, AFQ/tractography.py, AFQ/utils/parallel.py, doc/notebooks/afq-hcp-data.ipynb, doc/notebooks/afq-stanford-data.ipynb, examples/plot_afq_api.py, examples/plot_tract_profile.py
More work on the API. Needs a lot more thinking.
=> WIP: putting together a pipeline

AFQ/dki.py, bin/pyAFQ_mdki
1) I added mdki model to dki.py
2) I created the script pyAFQ_mdki that runs the mdki model
=> Add mean dki model

.travis.yml, AFQ/dki.py
Let's see if we can install straight from master on travis, before merging #51 (might make tests there pass, and we can get rid of "fixes"!)
=> Try installing dipy from the source on Github.

AFQ/dki.py, bin/pyAFQ_dkimicro
Add fit_dkimicro to dki.py and pyAFQ_dkimicro in bin
=> NF: DKI microstructure

AFQ/segmentation.py
=> Store distances from first loop over bundles for reuse in second loop.

AFQ/segmentation.py, AFQ/tests/test_segmentation.py
=> Fall-back behavior if there is no probability map.

AFQ/segmentation.py, AFQ/tractography.py, AFQ/utils/volume.py
step size is by voxel not by mm. 2 steps per voxel is reasonable. We could do more. But probably not needed
=> updated tracking params

AFQ/api.py, AFQ/dki.py, AFQ/dti.py, AFQ/tests/test_api.py, AFQ/tests/test_dki.py, AFQ/tests/test_dti.py, AFQ/utils/bin.py, bin/pyAFQ, bin/pyAFQ_dki, bin/pyAFQ_dki_predict, bin/pyAFQ_dkimicro, bin/pyAFQ_dti, bin/pyAFQ_dti_predict, bin/pyAFQ_mdki
For now, added a method that combines tract profiles, and the CLI is still WIP, to be added in subsequent commits.
=> Add a CLI that runs the whole thing

AFQ/tests/test_api.py, bin/pyAFQ
=> Simplify CLI to always generate bundles and ROIs.

AFQ/api.py, AFQ/registration.py, AFQ/segmentation.py, AFQ/tests/test_api.py, AFQ/tests/test_registration.py, AFQ/tests/test_segmentation.py, AFQ/utils/volume.py, bin/pyAFQ
This seems to work well on at least one dataset I've tried.
@jyeatman: could you try this with the dataset you were working with?
=> Apply a stricter cleaning criterion.

docs/source/installation_guide.rst
Does this seem sufficient @jyeatman?
=> Add a note that points people to use 3.6 or 3.7.

.travis.yml, AFQ/api.py, AFQ/data.py, AFQ/dti.py, AFQ/segmentation.py, AFQ/tests/test_api.py, AFQ/tests/test_csd.py, AFQ/tests/test_dki.py, AFQ/tests/test_dti.py, AFQ/tests/test_registration.py, AFQ/tests/test_segmentation.py, AFQ/tractography.py, AFQ/utils/parallel.py, AFQ/utils/streamlines.py, AFQ/utils/testing.py, AFQ/viz.py, Makefile, examples/plot_afq_api.py, requirements-dev.txt
In particular, line-space *before* binary operators from now on.
=> MAINT: Pin pytest version. For flake8 choose the rules that Travis chooses.

AFQ/segmentation.py, examples/plot_tract_profile.py, requirements-dev.txt, requirements.txt
Before we start merging ongoing work, it would be good to get all the tests passing again. 
This branch will hopefully get it all green once more.
=> Fix failing tests

examples/plot_tract_profile.py
Update following changes in #65
=> Fix the example to the newest API.

AFQ/api.py, AFQ/dki.py, AFQ/dti.py, AFQ/registration.py, AFQ/segmentation.py, AFQ/tests/test_dki.py, AFQ/tests/test_dti.py, AFQ/tests/test_registration.py, AFQ/tests/test_scripts.py, AFQ/tractography.py, AFQ/utils/models.py, AFQ/utils/testing.py, AFQ/viz.py, examples/plot_afq_api.py, examples/plot_tract_profile.py
=> Change all calls of get_data to get_fdata

AFQ/registration.py, examples/plot_tract_profile.py
Should resolve some of the issues raised in #123
=> BF: syn_register_dwi returns a tuple as output.

examples/plot_tract_profile.py
This (@36000's idea!) speeds up the example, because tracking was the
bottle-neck. Next, to get CircleCI to build the examples for us!
=> Seed for tracking only in the way-point ROIs.

AFQ/_fixes.py, AFQ/csd.py, AFQ/segmentation.py, AFQ/tests/test_tractography.py, AFQ/tractography.py, examples/plot_recobundles.py, examples/plot_tract_profile.py
So far, I've managed to make the Recobundles functionality work. Still working on the waypoint ROI approach.
=> Refactoring examples to DIPY 1.0 I/O API

AFQ/api.py, bin/pyAFQ
=> BF: Use new API in saving tracking results.

.github/workflows/ci.yml
Just trying to see what this looks and feels like
=> Trying out Github Actions

.github/workflows/ci.yml, AFQ/segmentation.py, Makefile
=> Adds TQDM (again)

docs/source/usage.rst
@gkiar : is this explanation clear/sufficient?
=> Adds an example of downloading some example data and organizing it.

.mailmap, .maintenance/update_changes.sh, .maintenance/update_zenodo.py, .zenodo.json, requirements-dev.txt, setup.py
A couple of small tools to update CHANGES and the zenodo record. Lifted (with added license) from nipreps
=> Maintenance tools

AFQ/api.py
As I work through using the API, I am putting any changes I make in this pull request. So far:
1. Allowing relative paths for dwi_folder, anat_folder (sub_dir is redundant as sess contains full path already)
2. Small additions to documentation
3. Using f strings for paths
4. Moved helper functions into the class
5. added force recompute
=> Api Usability

AFQ/api.py, AFQ/tests/test_api.py
reg_prealign is sometimes used and assumed to exist. This causes errors when use_prealign is set to False.
=> More API Fixes

AFQ/api.py, AFQ/csd.py
=> Automatically infer sh_order

.github/workflows/test.yml, AFQ/tests/test_api.py, bin/pyAFQ, requirements-dev.txt
Adds the work from #229 into the CLI.
=> Integrate the bundle gif viz into the CLI.

AFQ/api.py, AFQ/data.py, AFQ/segmentation.py, AFQ/tractography.py, bin/pyAFQ
=> Adds a flag to save intermediate variables within Segmentation

AFQ/data.py
=> BF: Actually use the user-provided path for saving HCP files.

requirements.txt
=> Update reqs 253

AFQ/api.py, bin/pyAFQ, requirements.txt
Uses xvfb_wrapper to handle virtual display on aws in api
=> Use xvfb_wrapper for aws

AFQ/api.py, AFQ/tests/test_viz.py, AFQ/viz.py
=> Visualize all tract profiles for a scalar in one plot

AFQ/viz.py, requirements.txt
New pybids version caused errors with tensorflow.
=> Fix two bugs, makes tests work

.github/CONTRIBUTING.md
=> Add instructions for disabling github actions on forked repos.

AFQ/api.py
I found this bug while looking at FA registration. @arokem  I wonder if this is the source of some of our registration problems.
=> make_bundle_dict should only be called after reg_template is settled

.zenodo.json, requirements.txt
See https://github.com/templateflow/templateflow/issues/75
=> Bump pybids to 0.11.1

AFQ/segmentation.py
=> Make save intermediates folder if it does not already exist

AFQ/api.py
This is a convenient function that should reduce boiler plate code.
Closes #301
=> std_export function

AFQ/api.py, AFQ/viz/utils.py, docs/source/usage.rst, pyafq_cli.json
=> Remove hcc from defaults

AFQ/api.py
It's possible this will find more bundles, requiring tests to be updated.
=> Make power maps the default for registration

AFQ/segmentation.py, AFQ/tests/test_segmentation.py, examples/plot_tract_profile.py
Address #157.
This is in the right direction, but requires more validation.
=> Clips streamlines by the inclusion ROI.

AFQ/tests/test_api.py, AFQ/utils/bin.py, bin/pyAFQ
Closes #347,  Closes #346 
TODO:
=> Auto doc fix

AFQ/api.py
Making gifs using plotly instead of fury has always been slow. Plotly is better at making interactive html. That said, it should be possible. For 0.4, maybe we should warn users to not use plotly to make gifs (like in this PR) until we get to the bottom of why kaleido is taking so long (see: https://github.com/yeatmanlab/pyAFQ/issues/349#issuecomment-673738530). We could also throw an error.
=> Export what is natural to the viz library

AFQ/api.py, AFQ/data.py, AFQ/viz/utils.py
=> Add upload_to_s3, download_and_combine_afq_profiles

AFQ/api.py
=> Remove unnecessary check

AFQ/api.py
=> Timing dict name mismatch bug fix

AFQ/_fixes.py, AFQ/tests/test_tractography.py, AFQ/tractography.py
Addresses #334. For now, I have done the naive thing of assuming that these objects are duck-typing. From my local testing, it looks like it's going to be a bit more complicated than that. We might need to do some more work in the `_track` function to be able to use both objects.
=> Adds ParticleFilteringTractography.

AFQ/data.py, AFQ/tests/test_data.py
=> Convert local_directories set to list

.github/workflows/docbuild.yml, AFQ/api.py, docs/source/conf.py, examples/plot_afq_api.py
The column names were updated in #279, and this follows that update.
The note that used to be here is no longer correct 🎉 
Also, we might want to always run this in the CI. Let's see how long this takes.
=> Update example to serve as a CI target

AFQ/api.py, AFQ/mask.py, AFQ/segmentation.py, AFQ/utils/tests/test_volume.py, AFQ/utils/volume.py, examples/plot_tract_profile.py
In response to #397 . Does not fix issue but makes a more clear error.
=> Raise error earlier for empty ROI

.github/workflows/nightly2_test.yml, .github/workflows/test.yml, AFQ/tests/test_api.py
This should help with OOM error or at least binary search for the test causing it.
=> Divide nightly test into 2; have nightly tests only do nightly tests

AFQ/api.py, AFQ/mask.py, AFQ/tests/test_api.py, AFQ/tractography.py, AFQ/utils/bin.py, AFQ/viz/utils.py
Closes #404 , Closes #403, Closes #391
=> Many minor bug fixes

.github/workflows/nightly3_test.yml, AFQ/tests/test_api.py
This will help us find a bad test / split up the memory consumption.
=> Further subdivide nightly tests

.github/workflows/docbuild.yml, .github/workflows/test.yml, setup.cfg
This is on top of #359 and adds a Python 3.8 test run.
=> Python 3.8

AFQ/tractography.py
It's a bit hard to test and demonstrate this as a bug, but this produces nonsense streamlines in practice. It also makes sense when you think about it.
=> BF: Register the PVE to the parameters.

AFQ/api.py, AFQ/segmentation.py, AFQ/tests/test_api.py
=> Automatically choose bundle names for recobundles

AFQ/api.py, AFQ/tests/test_api.py
=> Allow user to input custom tractography

setup.cfg
This is a necessary requirement to import certain dipy files that we use.
=> Add packaging requirement

AFQ/api.py, AFQ/data.py, AFQ/tests/test_api.py, AFQ/viz/utils.py
=> Remove whole brain from bundle dict for reco viz

AFQ/api.py, AFQ/utils/stats.py, AFQ/utils/tests/test_stats.py, AFQ/viz/utils.py, setup.cfg
=> Update plots to paper Quality

AFQ/api.py, AFQ/viz/utils.py
=> Rename profile columns back to standard column names

AFQ/mask.py, AFQ/tests/test_api.py, AFQ/tests/test_tractography.py, AFQ/tractography.py
=> Add PFT Mask.

AFQ/api.py, AFQ/data.py, AFQ/segmentation.py, AFQ/tests/test_segmentation.py, examples/plot_recobundles.py
Addresses #421, but we need to think about how this integrates with work already done in #420.
=> Adds 80-bundle atlas for RB

AFQ/viz/utils.py
Minor adjustment to fonts, sizes. Added median reliability bars.
=> Adjusting group comparison figures

AFQ/data.py, docs/source/_static/custom.css, docs/source/conf.py, docs/source/contributing.rst, docs/source/index.rst, docs/source/installation_guide.rst, docs/source/usage_templ.rst, examples/plot_afq_api.py
These are some updates as result of my review last week.
=> Updating pyAFQ documentation

AFQ/api.py
1. Adds an extension to output.
2. Adds a column of the different steps.
=> Fixes the timing table

AFQ/api.py, AFQ/tests/test_api.py
=> FIX: remove whole brain from bundle list for sl count when using recobundles

AFQ/api.py, AFQ/tests/test_api.py
=> Adds total number of streamlines, to complete the sl counts table.

AFQ/api.py, AFQ/tests/test_api.py
=> Allow reg subject to be bids filters; refactor getting stanford data into temp folder

AFQ/api.py
=> Apply brain mask to subject img before registration

AFQ/segmentation.py, AFQ/tests/test_api.py, examples/plot_recobundles.py
=> Reg algo automatically chosen based on whether mapping is provided, syn mapping for sls fixed, recobundle defaults updated

AFQ/viz/utils.py
=> FIX: Downsample number of streamlines vizzed down to 200 when vizzing all bundles

docs/Makefile
addressing enhancement request #485
=> enh adding distclean and realclean targets for sphinx build

AFQ/tractography.py, AFQ/utils/tests/test_volume.py, AFQ/utils/volume.py
Compute a dice coefficient using density maps from #476
=> ENH: Dice coeff

.github/workflows/nightly2_test.yml, .github/workflows/nightly3_test.yml, .github/workflows/nightly4_test.yml, .github/workflows/nightly_test.yml, .github/workflows/test.yml, AFQ/tests/test_api.py
=> Split off nightly 4 from nightly 3, nightly rests run python 3.8

AFQ/tractography.py
=> FIX: Update tractography max_length docstring to be consistent

AFQ/api.py
This should fix nightly test 4
=> FIX: update reg_subject arg checking to include dicts

AFQ/models/csd.py, AFQ/models/dki.py, AFQ/models/dti.py, AFQ/registration.py, AFQ/segmentation.py, AFQ/utils/models.py
Closes #504 . I believe this is all of them.
=> FIX: Update all b0_thresholds to 50

AFQ/viz/fury_backend.py, AFQ/viz/plotly_backend.py, AFQ/viz/utils.py
=> FIX: Plotly viz bug fixes, and update to custom bundles

AFQ/api.py
=> FIX: specify that the b val range is inclusive

AFQ/api.py, AFQ/tests/test_api.py
=> FIX: Reco80 fixes

.github/workflows/nightly2_test.yml, .github/workflows/nightly3_test.yml, .github/workflows/nightly4_test.yml, .github/workflows/nightly_test.yml, .github/workflows/test.yml, AFQ/tests/test_api.py, setup.cfg
@arokem I think this may help with the memory issues the nightly tests can run into.
=> FIX: Remove xvfb from being needed in tests

AFQ/segmentation.py, AFQ/tests/test_segmentation.py
=> BF: Reset the input tractogram space to what you originally got.

.github/workflows/test.yml, AFQ/tests/test_api.py
=> NIGHTLY: move reco80 to 4; break up nightly 3 to isolate bug

.github/workflows/nightly5_test.yml, AFQ/tests/test_api.py
I think these changes will get it so the nigthly tests are passing.
=> Update test_init to additional df columns; add nightly 5 test yml

AFQ/tests/test_api.py
this will bring test times back down.
=> Put msmt in nightly 3

AFQ/viz/utils.py
=> Save non anat positioned bundles in their own plots

AFQ/data.py
One way to address and resolve #449
=> Warn when templateflow creates directory

examples/plot_callosal_tract_profile.py, examples/plot_recobundles.py, examples/plot_tract_profile.py
=> Adds prealign stage to the examples.

AFQ/utils/tests/test_volume.py, AFQ/utils/volume.py
Adds the option to calculate a wDSC (as in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6339903/). Defaults to True.
=> [ENH] add weighted option for dice

AFQ/segmentation.py, AFQ/tests/test_segmentation.py
=> adding nb_streamlines to segmentation parameters

AFQ/api.py, AFQ/tests/test_api.py
=> initialize for subject and session pairs where dwi files exist

AFQ/api.py
See: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3136876/
=> NF: Adds DKI AWF to scalars.

AFQ/utils/tests/test_volume.py, AFQ/utils/volume.py
=> [ENH] Allow user to optionally normalize density map maximum values to 1

docs/source/usage/data.rst
=> DOC: Explain that trk files are saved in RASMM.

AFQ/api.py
=> [FIX] calculate sl counts on the spot

.github/workflows/docbuild.yml, .github/workflows/nightly2_test.yml, .github/workflows/nightly3_test.yml, .github/workflows/nightly4_test.yml, .github/workflows/nightly5_test.yml, .github/workflows/nightly_test.yml, .github/workflows/test.yml, docs/source/installation_guide.rst, setup.cfg
=> Drop Python 3.6 support.

AFQ/tests/test_api.py
Updates data frame shape to new values.
=> Fix test_AFQ_init, may allow nightly 3 to pass

AFQ/api.py
Specifically, pre-registration takes ~5x longer than mapping on pre-K data, so it needs to be in the timing file.
=> Add more timing information

AFQ/api.py, AFQ/tests/test_api.py, examples/plot_afq_api.py
=> [WIP] Allow user to only use prealign in registration

setup.cfg
This may be fix the tests/docs failing with error:
```
Extension error:
Could not import extension updatedocs (exception: numpy.core.multiarray failed to import)
```
=> Update numpy version

AFQ/segmentation.py
=> export endpoint ROI when saving intermediates

AFQ/viz/utils.py
Some of the tweaks to the plotting code to make it output SVGs and be compatible with gridspec (accept ax, fig as arguments).
=> More plotting tweaks, gridspec compat

AFQ/api.py, AFQ/tests/test_api.py
gives user option to calculate the median tract profile, as well as provide their own weighting scheme.
=> Median tract profile

AFQ/api.py, AFQ/data.py, AFQ/tests/test_api.py, setup.cfg
this is the version qsiprep uses
=> [WIP] [FIX] try to make pyafq play nice with pybids 0.9.3

docs/source/conf.py, docs/source/index.rst, setup.cfg
Trying out different documentation layouts.
Is there an easy way to generate the docs without running the examples?
=> [Doc] try new docs layout

AFQ/segmentation.py
These are more lenient parameters suggested by Chandio in a recent meeting. They have yet to be tested on our HCP pipeline.
=> [FIX] More lenient reco defaults

setup.cfg
I have been getting this error otherwise:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-805623dd75d1> in <module>()
----> 1 from AFQ import api
2 import AFQ.data as afd
3 frames
/usr/local/lib/python3.7/dist-packages/s3fs/core.py in <module>()
9 from fsspec.spec import AbstractBufferedFile
10 from fsspec.utils import infer_storage_options, tokenize
---> 11 from fsspec.asyn import AsyncFileSystem, sync, sync_wrapper, maybe_sync
12
13 import aiobotocore
ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (/usr/local/lib/python3.7/dist-packages/fsspec/asyn.py)
```
=> BF: Update s3fs version.

examples/cloudknot_example.py, examples/cloudknot_hcp_example.py
Sendy found a few bugs/improvements in the cloudknot example
=> [FIX] cloudknot example fixes

AFQ/api.py, examples/cloudknot_example.py, examples/cloudknot_hcp_example.py
Credit to Adam and Sendy for finding and suggesting fixes.
=> [FIX] download and combine profile fixes and improvements

.github/workflows/docker_afqsi.yml, .github/workflows/docker_pyafq.yml
Addresses #666 
Based on https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
=> Builds a tagged image when a tag is pushed.

AFQ/api.py
=> Allow for other derivatives folders when downloading and combining

AFQ/tasks/data.py, AFQ/tasks/mapping.py, AFQ/tasks/tractography.py, AFQ/tests/test_api.py
fixes for pimms PR for nightly tests. Mostly updating tests, also fixing an msmt problem. I am going to merge this now, @arokem , so that the nightly tests run overnight and we see what else needs to be fixed.
=> [FIX] Nightly pimms fixes

AFQ/tasks/mapping.py, AFQ/tests/test_api.py
More minor fixes for the nightly tests! this also fixes a bug which caused an error in SLR.
=> [FIX] Nightly pimms fixes2

AFQ/definitions/mask.py, AFQ/tasks/data.py
This should fix the nightly pft task
=> [FIX] Mask getters have to be aware of whether they are being called from data task

docs/source/usage/converter.rst, docs/source/usage/data.rst, examples/plot_bids_layout.py
This PR is meant to address the issues raised in #695
=> [DOC] Bids layout clarifications

AFQ/api.py, setup.cfg
=> [ENH] AFQ-Browser Integration

.github/workflows/docker_afqsi.yml, .github/workflows/docker_pyafq.yml
Based on https://github.community/t/how-to-get-just-the-tag-name/16241/21
=> BF: Fix docker builds 

examples/plot_bids_layout.py
see https://github.com/bids-standard/bids-bep016/issues/22
=> Fixes broken link in BIDS example 

docs/source/developing/definitions.rst, docs/source/developing/index.rst, docs/source/developing/tasks.rst
This is a rough draft for developer documentation for adding tasks and definitions
=> [DOC] Add developer documentation for adding tasks and definitions

AFQ/tests/test_api.py
=> [TESTFIX] Update nightly test to match new, more specific error message

AFQ/api.py, AFQ/tasks/viz.py, AFQ/tests/test_api.py
=> [Fix] Better export all behavior

AFQ/data.py, AFQ/tasks/viz.py, docs/source/conf.py, examples/plot_optic_radiations.py
=> WIP: Add OR fetcher and example

AFQ/tasks/data.py, AFQ/tests/test_api.py
These scalars include scalars that mAFQ already calculates.
=> [ENH] add more scalars, add one to the test

docs/source/usage/scalars.rst
=> [DOC] Adds an example to the custom scalar docs

AFQ/api.py, AFQ/tasks/data.py, AFQ/tasks/mapping.py, AFQ/tasks/segmentation.py, AFQ/tasks/tractography.py, AFQ/tasks/viz.py, docs/source/developing/tasks.rst
This adds some basic documentation for the myafq.export_ functions (like myafq.export_b0()). This documentation can be seen by doing help(myafq). I will post a picture shortly of what these changes look like.
=> [DOC] Generate simple docs for export function outputs

AFQ/api.py
=> BF: Resample ROI for custom bundledict as well

.github/workflows/docker_pyafq.yml
I think these need to be in quotes
=> [FIX] Attempt to fix the docker push for tags

AFQ/api.py, AFQ/tasks/tractography.py
but allow processing to continue (maybe some subjects have tractography, while others do not). This has been tested.
=> [ENH] alert users when custom tractography is not found for a given sub/ses

AFQ/api.py, AFQ/data.py
Lets wait and rebase this once #764 is merged
=> [ENH] allow user to pass arguments to pyBIDS BIDSLayout

CITATION
I think that this might create a link on the repo's front page that
directs to this file.
=> Adds CITATION file.

AFQ/api/group.py, AFQ/api/participant.py, docs/source/conf.py, docs/source/developing/definitions.rst, docs/source/sphinxext/kwargsdocs.py, docs/source/usage/docker.rst, docs/source/usage/scalars.rst, setup.cfg
=> [DOC] fix minor erros in documenation

AFQ/_fixes.py, AFQ/tests/test_api.py
Fixes two error:
1. Simple typo within test, introduced by recent bundle dict PR
2. Add a new Error to the try/catch for cvx.Problem().solve(), because of recent cvxpy update
=> [FIX] Some fixes for nightly tests

AFQ/segmentation.py
This may be useful for sub-bundles.
=> [ENH] Allow segmentation tie breakers to be settled by distance from ROI

setup.cfg
The old version of moto may be causing the errors in circleci tests.
=> Upgrade moto

AFQ/tests/test_api.py
=> Reduce number of streamlines in nightly reco80 test

AFQ/utils/bin.py, bin/pyAFQ
This will be used to update QSIprep more easily in the future.
=> [ENH] Autogenerate two separate QSIprep pipelines

AFQ/definitions/image.py, AFQ/tasks/data.py, AFQ/tasks/decorators.py, AFQ/tasks/mapping.py, AFQ/tests/test_api.py, bin/pyAFQ
Updates tests and fixes small bug introduced by #825
=> [FIX] update nightly tests and fix kwargs

AFQ/tasks/viz.py, examples/plot_afq_api.py, examples/plot_afq_callosal.py, examples/plot_afq_reco80.py, examples/plot_baby_afq.py
=> [ENH] Return path to single viz file if its generated

AFQ/tasks/tractography.py, AFQ/tests/test_api.py, AFQ/utils/bin.py, README.md, bin/pyAFQ, docs/source/index.rst
=> [ENH] minor docs updates and qsiprep changes

.zenodo.json
1. Moves John to the "creators" section.
2. Updates Adam's affiliation.
3. Adds David as a contributor.
Please confirm @richford, @36000, @bloomdt-uw
=> MAINT: Refreshes the zenodo metadata file.

.github/workflows/test.yml
https://github.com/nipy/nibabel/releases/tag/4.0.0rc0
We might want to think about how to integrate this into our regular
testing. Partially addresses https://github.com/yeatmanlab/pyAFQ/issues/760.
=> TST: Test the nibabel release candidate.

AFQ/api/bundle_dict.py, AFQ/api/group.py, AFQ/tasks/tractography.py, AFQ/viz/utils.py, examples/plot_optic_radiations.py, setup.cfg
Tested locally using fury on small dataset.
=> [ENH] Add montage and combine bundle to GroupAFQ

AFQ/api/group.py, AFQ/data/fetch.py, AFQ/data/s3bids.py, AFQ/tasks/segmentation.py, setup.cfg
I am opening this PR to explore what we need to change in order to be able to upgrade pybids to the more current version.
=> Upgrade pybids.

AFQ/tests/test_api.py
SLR test is also revamped to be much faster (a few minutes or less)
=> Fix nightly tests

docs/source/developing/index.rst
This adds a brief description of the layout of pyAFQ which new developers may find helpful.
=> [DOC] add pyafq overview desciption

AFQ/data/s3bids.py
So at least I don't have to stumble around every time I try doing this.
=> DOC: Document S3BIDS access examples.

AFQ/api/bundle_dict.py
In a later PR we can add an example for this, which we can use to automatically error check this.
=> [FIX] Some pediatric bundle dict fixes

AFQ/api/group.py, AFQ/tasks/decorators.py, AFQ/tasks/segmentation.py, AFQ/utils/volume.py, examples/plot_afq_callosal.py, examples/plot_callosal_tract_profile.py
Here is a good place to have a discussion about what options should be available for the group density map.
=> [ENH] Density task

AFQ/tests/test_api.py
On my laptop, I get intermittent failures on this test, when the seed is not fixed.
=> TST: Fix a random seed for this test.

examples/plot_optic_radiations.py
This resolves the issue we are currently seeing on master, at least on my laptop.
=> DOC: Fix the random seed for the OR example.

docs/source/reference/index.rst
=> Adds back reference documentation to reference section.

setup.cfg
=> Update setup.cfg with newer pybids

AFQ/api/participant.py, AFQ/definitions/mapping.py, AFQ/registration.py, AFQ/tests/test_registration.py, docs/source/howto/docker.rst, examples/howto_examples/plot_afq_fwdti.py, gpu_docker/Dockerfile, pyafq_docker/Dockerfile, setup.cfg
Cannot get this to work right now. Will ultimately be handled by nitransforms.
Also fixes a bug in the clobber command.
Also removes unused register_dwi function which is now in dipy as `register_dwi_series`
=> [FIX] Remove itk

AFQ/tasks/data.py, AFQ/tasks/tractography.py, docs/source/howto/installation_guide.rst, docs/source/howto/usage/kwargs.rst, docs/source/howto/usage/methods.rst, docs/source/index.rst, docs/source/reference/kwargs.rst, docs/source/reference/methods.rst
Started rewriting documentation
=> added more documentation of dependencies

AFQ/api/group.py, AFQ/api/participant.py, AFQ/viz/fury_backend.py, AFQ/viz/plotly_backend.py, AFQ/viz/utils.py, examples/tutorial_examples/add_custom_bundle.py, examples/tutorial_examples/plot_optic_radiations.py
add a bundle montage for each subject
=> [ENH] Bundle montage

AFQ/utils/path.py
=> [FIX] delete folders in AFQ derivatives when clobbering

AFQ/api/participant.py
=> Remove unused MPL import

AFQ/tasks/decorators.py
Should help address this error: https://github.com/yeatmanlab/pyAFQ/actions/runs/6182806983/job/16783267110#step:6:101
This passes locally on my laptop.
=> Fence the TRX test by checking whether TRX is installed.

docs/Makefile, docs/source/reference/methods.rst
Quite useful for quick debugging of changes to documentation.
=> Adds an option to build the docs without running the examples.

AFQ/data/fetch.py
=> [enh] set afq home

AFQ/api/bundle_dict.py, AFQ/segmentation.py, AFQ/tasks/segmentation.py, AFQ/tests/test_api.py, AFQ/utils/bin.py, docs/source/howto/usage/kwargs.rst, docs/source/reference/bundledict.rst, docs/source/reference/kwargs.rst, examples/howto_examples/vof_example.py, examples/tutorial_examples/add_custom_bundle.py, examples/tutorial_examples/baby_afq.py
Does mahalanobis cleaning per bundle, and updates babyAFQ dictionary to new system.
=> [ENH,FIX] Integrate more steps into the segmentation pipeline

AFQ/api/group.py, AFQ/api/participant.py, AFQ/api/utils.py, AFQ/data/fetch.py, AFQ/tasks/data.py, AFQ/tasks/decorators.py, AFQ/tasks/segmentation.py, AFQ/tests/test_api.py, AFQ/utils/path.py, examples/tutorial_examples/plot_001_afq_api.py
Whats remaining is to test some of these new features
=> ENH allow removal of profiles.csv; allow setting n_nodes in profile; make callosal bundles the default

AFQ/_fixes.py, AFQ/tests/test_fixes.py, examples/tutorial_examples/plot_001_afq_api.py
I have tried this on the stanford hardi dataset example, but it would be nice to try on a few other subjects before we merge.
=> [FIX] More correct way of calculating mahal distances for cleaning

AFQ/data/fetch.py, AFQ/tests/test_data.py, examples/howto_examples/plot_accoustic_radiations.py
Also removes some code we no longer use
=> [WIP/ENH] add AR from endpoint ROIs

examples/tutorial_examples/plot_003_viz.py
=> DOC: Small fixes to the visualization example.

AFQ/tests/test_api.py
=> [FIX] update this nightly test

AFQ/tasks/data.py
This adds a new anisotropic kurtosis parameter. 
It also makes DKI tand fa/md/kfa/mk the default scalars for multishell data, and DTI FA/MD the default for single shell (our current default)
=> [ENH] add anisotropic kurtosis, make dki default?

AFQ/definitions/image.py, AFQ/definitions/mapping.py, AFQ/definitions/utils.py, AFQ/tasks/mapping.py, AFQ/tasks/segmentation.py, AFQ/tests/test_api.py
This solves two problems:
1. Fix files being assigned to the wrong session
2. Allow for subjects to have missing scalars
=> [ENH/FIX] Smarter file finding

.github/workflows/docbuild.yml, examples/howto_examples/plot_stages_of_tractometry.py
More visualizations and animations. Supersedes #1016
=> Adds an example to plot stages of tractometry.

docs/source/explanations/bundle_orientation.rst, docs/source/explanations/index.rst, docs/source/reference/bundledict.rst, docs/source/reference/kwargs.rst, docs/source/reference/methods.rst
once we merge this we might want to cut a minor release (1.3.1?) to update the docs page
=> [DOC] add bundle orientation explanation

AFQ/segmentation.py, AFQ/tasks/segmentation.py, AFQ/tests/test_segmentation.py, AFQ/utils/streamlines.py
Fixes #1110
Adds info from bundle_dict to json sidecars for individual bundles and the large bundle file.
=> [ENH] add more information from bundle dict into jsons

docs/source/reference/bundledict.rst
Enumerate the order of the bundle recognition steps
Explain save_intermediates
=> [DOC] Some improvements to the documentation based on conversations during the hackathon

examples/howto_examples/baby_afq.py
Added additional information about modifying sbv_lims_bundles for low FA values in baby bundles
=> [DOC] Update baby_afq.py

AFQ/tasks/data.py, AFQ/tasks/tractography.py, AFQ/tractography/tractography.py
Tried to add RUMBA-SD based on https://docs.dipy.org/stable/examples_built/fiber_tracking/tracking_rumba.html and https://docs.dipy.org/stable/reference/dipy.reconst.html#dipy.reconst.rumba.RumbaSDModel
=> [ENH] Added RUMBA-SD to data.py

AFQ/tasks/data.py
=> Check bvals on dki
