AFQ/data.py

This PR adds the JHU ROI templates, and clarifies the difference with the callosal templates. I have also switched to using figshare, instead of Researchworks, because it's easier to deal with.

New templates

---

AFQ/api.py
AFQ/registration.py
AFQ/tests/test_api.py
AFQ/tests/test_registration.py
AFQ/utils/streamlines.py
AFQ/utils/tests/test_streamlines.py
examples/plot_tract_profile.py

Use the DIPY I/O for streamlines, instead of our own.

---

examples/plot_recobundles.py

It's a bit long and windy right now, but at least some of that is because I had to figure out how to use the atlas to seed in the location of the bundles in the subject space. Neverthless, useful. After more testing, we should proceed to bake this stuff into the API.

Adds an example using RecoBundles to do the segmentation.

---

AFQ/_fixes.py
AFQ/tractography.py

Move check for streamline length into tracker, so too small or too large streamlines can be thrown out without having to be saved.

Early track checks

---

AFQ/api.py
AFQ/data.py
AFQ/segmentation.py
AFQ/tests/test_api.py
AFQ/tests/test_registration.py
AFQ/tests/test_segmentation.py
examples/plot_recobundles.py
examples/plot_tract_profile.py

In the process of putting segmentation into its own class. Added logging, option to resample. trying numba.

Segmentation Refactoring and Other Updates

---

AFQ/api.py
AFQ/data.py
AFQ/segmentation.py
AFQ/tests/test_api.py
AFQ/tests/test_segmentation.py
AFQ/utils/streamlines.py
AFQ/utils/tests/test_streamlines.py
AFQ/utils/volume.py
examples/plot_tract_profile.py

We should use StatefulTractogram methods for spatial transformations wherever possible (instead of `transform_tracking_output`).

Transform streamlines using SFT methods.

---

AFQ/segmentation.py
AFQ/tests/test_segmentation.py
examples/plot_tract_profile.py

For now, just the failing unit test. Implementation to follow.

`clean_by_endpoints` should be able to return the indices.

---

AFQ/segmentation.py

Hi, 
this fix corrects the warping of ROI and probability maps in segmentation.py. It had been done with using the forward direction of the warp operation used to warp native on template. Now it is done with the inverse, resulting in ROI and probmap, which were previously registered to template, being warped into native space. 
Also, added debugging lines, which are currently commented-out, in preparation for an optional debugging feature mode that allows step by step tracking of problems with image registration.
_aNNe

Fix warping

---

AFQ/__init__.py
AFQ/api.py
AFQ/data.py
AFQ/registration.py
AFQ/segmentation.py
AFQ/tests/test_api.py
AFQ/tests/test_registration.py
examples/plot_recobundles.py
examples/plot_tract_profile.py
requirements.txt

This has the added benefit that we can get a brainmask for our registration from the same place (which is the default behavior implemented here).

Read the MNI template from templateflow, instead of DIPY.

---

AFQ/api.py
AFQ/viz.py

Fixes #247
It turns out that we don't need 40 colors. This is only needed in AFQ-Browser
because we need to be able to highlight the picked bundles.
This means that the code can be simplified quite a bit. This commit also
clarifies and simplifies the logic, including comments. And adds a docstring.
Changes in the API module to remain consistent.

BF: Use Tableau 20 colors for the 20 waypoint-defined bundles.

---

AFQ/api.py

Save mask as float32, so that we can open it in MI-Brain.

---

requirements-dev.txt

The numpydoc version 1.0.0 causes the error:
`Handler <function mangle_docstrings at 0x1124e5400> for event 'autodoc-process-docstring' threw an exception`
In our documentation tests. I am not sure why.

Fixed numpydoc version to 0.9.2

---

AFQ/api.py

Show session and subject in all file names. Moved common inclusions for file names into fname function. Some pep8 fixes.

Api File Naming

---

AFQ/data.py

Our last attempt to fix the path names in fetch_hcp introduced another bug. This PR makes it use the same path names as the other fetch functions.

Bring fetch_hcp into alignment with other fetch functions

---

AFQ/tractography.py
pyafq_cli.json

This parameter sets the random_seed when random_seeds is True.

Added random_seed parameter in tractography

---

AFQ/api.py
AFQ/tests/test_api.py

Instead of a scalar column with the names "dti_fa", "dti_md" and a profiles column with their corresponding values, each scalar gets its own column. closes #277

Profile format changed to be less tall and more wide, like mAFQ

---

setup.py

setup.py now looks for files of the form `'requirements-*.txt' `and uses them for the EXTRAS_REQUIRE argument.
Currently allows: `pip install 'pyAFQ[dev]'`
Automatically finds more extra setups when new files are added.
For example, if `requirements-fury.txt` were added, this would find that file and make a `'pyAFQ[fury]'` extra setup.

Extra requirements feature added, consistent with current requirement files

---

.maintenance/update_zenodo.py
requirements-dev.txt

FuzzyWuzzy is GPLv2 licensed which would force you to licence the whole project under GPLv2.
For this reason this Pullrequest replaces FuzzyWuzzy with  [rapidfuzz](https://github.com/maxbachmann/rapidfuzz) which is implementing the same algorithm but is based on a version of fuzzywuzzy that was MIT Licensed.
Rapidfuzz is:
- Mit licensed so it can be used with the license used by this project
- Is faster than FuzzyWuzzy

use rapidfuzz instead of fuzzywuzzy

---

requirements-dev.txt
requirements.txt

Six is already in requirements.txt, with a different required version. Let's just remove the dev requirement since it is already in requirements.txt

Remove six

---

AFQ/api.py
AFQ/viz/fury_backend.py
AFQ/viz/plotly_backend.py
AFQ/viz/utils.py
requirements-plotly.txt

This allows plotly to export static images such as gifs without any complicated installs.
@arokem if this passes the tests, it should be ready to merge.
Closes #304

Kaleido instead of orcas

---

AFQ/utils/models.py

Resolves #56.
`prepare_data` returns the last Nifti1Image generated from `data_files` in order to replicate the pre-existing behavior. But was that intended? It seems that the old behavior was to return the Nifti1Image produced by running `nib.load()` on the last element of `data_files`. Is there something special about the last one?

Bvals preallocation

---

pyproject.toml

The hope is that the local version will be picked up from setup.py instead.
This should resolve the current breakage on master.

Remove this section of the pyproject.

---

AFQ/data.py

It seems to be working now. We made 3 fixes:
1. make directory for modality agnostic files if it does not exist
2. allow derivatives to download, which was broken before because the prefix was wrong
3. download the dataset description for derivatives by default whenever downloading a given derivative, if it exists

S3 Bids Fetch Fixes

---

AFQ/data.py

This will be useful with cloudknot. For example, imagine I want to use cloudknout to process 3 random subjects. Each process can use the same random seed, but be told to use either the first, second, or third subject out of the randomized list of subjects generated from the same seed.

Allow for selecting subject(s) by position after randomization

---

AFQ/tests/test_viz.py
AFQ/viz/utils.py

Throw error when backend is misnamed

---

AFQ/data.py

This PR forces `AFQ.data.S3BIDSStudy` instances to return only unique subject IDs for it's `._all_subjects` attribute. Previously, the presence of qsiprep report html files would cause duplicate entries in `._all_subjects`. This did not affect the `.subjects` attribute but was still annoying. This fixes that issue and returns a unique subject list.

Return a unique set of subjects in S3BIDSStudy._all_subjects

---

AFQ/api.py
AFQ/segmentation.py
AFQ/tests/test_bundles.py
setup.cfg

The load_tractogram in dipy v1.1.1 uses srow to get the affine information from a reference. However, some files have affine stored in the q info (q offset, pixdim), not s. This is fixed in the current dipy master, where they find the best source for affine information, but not dipy 1.1.1 .
Until a new version of dipy is released, we can use this PR with some datasets. This PR will probably not need to be merged, especially if a new version of dipy is releasing soon.

Update to Dipy 1.2.0

---

AFQ/api.py

As we are exporting the bundles, count the streamlines in each bundle, and store that in a CSV.

Streamline counts table

---

AFQ/tests/test_api.py

Should address failing nightly test, but the PR currently also includes testing for this, which should happen before merging.

Removes extraneous underscore.

---

docs/source/_progressbars.py
docs/source/conf.py

This enhancement follows from [suggestion by @arokem](https://github.com/yeatmanlab/pyAFQ/pull/476/files#r498533426) in #476 and uses the sphinx-gallery [resetting behavior for custom libraries](https://sphinx-gallery.github.io/stable/advanced.html#define-resetting-behavior-e-g-for-custom-libraries). 
It is also worth noting as currently implemented will run for all sphinx-gallery examples.

ENH Disabling progress bars for sphinx-gallery

---

AFQ/segmentation.py

FIX: updates docstring in clean_bundle which returns sft, not nib.streamlines

---

examples/plot_recobundles.py
examples/plot_tract_profile.py

This is related to [observation](https://github.com/yeatmanlab/pyAFQ/pull/476/files#r494815555 ) from #443 review. Updating RecoBundle and tract profile examples to place artifacts in corresponding subdirectory. Note that AFQ API does not produce any artifacts in the `examples` directory and therefore was not changed as part of this work.. For now just placed a `working_dir` variable in both examples. This should work for both build and local execution.
Figured this was sufficient for now, but I briefly considered passing the working directory variable as part of build process [see](https://sphinx-gallery.github.io/stable/configuration.html#passing-command-line-arguments-to-example-scripts).

adding separate example output directories to avoid name collisions

---

.gitignore
AFQ/viz/utils.py
examples/plot_callosal_tract_profile.py

Baseline commit. There are several other enhancements requests and issues that will follow from work on this pull request. I think the main concern I have at the moment is whether the descriptive text is sufficiently accurate and any additional recommended text that would enhance the interpretive value the anatomical images, ROIs, or streamline density maps. I will add few comments in the pull request to address specific areas of interest and concern. From this conversation, I will open separate issues and enhancement requests where needed.

ENH #443 Callosal Group Example

---

AFQ/api.py

This follows up on #474 to actually pass the msmt parameter so this model is used in fitting.

Actually use MSMT in API call

---

AFQ/api.py

This is not a good way to do this. In particular, it triggers
multiple rounds of recomputing, for what should have been
obvious reasons. For now, if a user wants to force recomputing
the best approach would be to delete files.

Eliminate `force_recompute` option.

---

AFQ/viz/fury_backend.py
AFQ/viz/plotly_backend.py
AFQ/viz/utils.py

Closes #571 . Apparently the plotly x axis counts in a different direction than our images

[FIX] Unflip Plotly x axis; multiple flexibility improvements in plotly plotting for paper

---

AFQ/api.py
AFQ/tests/test_api.py

I think that SLR registration in pyAFQ with waypoint ROI segmentation has always had this problem. It works significantly better with this fixed.
Note: SLR with recobundles is handled elsewhere and did not have this bug, only SLR with waypoint ROI approach has this bug.

[FIX] Put tg in rasmm first for SLR registration

---

AFQ/data.py
AFQ/tests/test_data.py

This is a utility function for handling user-provided ROIs that are registered to MNI space, but are stored with an affine that differs from MNI.

Read and resample ROI data.

---

AFQ/api.py
AFQ/data.py
AFQ/mask.py
AFQ/tests/test_api.py
AFQ/tests/test_mask.py
AFQ/tractography.py
docs/source/usage/data.rst

This PR traverses the BIDS hierarchy to find masks, bval files, and bvec files instead of assuming that they will be found in the same session. It is part bugfix, part enhancement because it also fixes the underscore error in `PFTMask.get_mask()`.
Traversing the hierarchy should allow it to interact with common output patterns from nipreps.

FIX: Traverse BIDS hierarchy to find masks, bvals, and bvecs

---

docs/source/conf.py
examples/cloudknot_example.py
examples/cloudknot_hcp_example.py

[ENH] Add cloudknot example

---

AFQ/api.py
AFQ/viz/fury_backend.py
AFQ/viz/plotly_backend.py

This is useful in baby brains for example, where one large FA value somewhere in the brain throws off our default scale of 0 to the maximum value.
Closes #547 .

[ENH] Allow the user to specify what range the color by volume should shade over

---

examples/plot_afq_reco80.py

[ENH] added reco80 example

---

AFQ/viz/fury_backend.py

This fixes a small bug, where x/y inputs were being ignored in setting the selected slice.

BF: Use the provided x and y inputs.

---

AFQ/data.py
examples/plot_bids_layout.py
examples/plot_other_tracking.py

@jyeatman : this is the example that shows how to use tractography outputs from another pipeline

DOC: Example that explores BIDS and includes tractography from another pipeline.

---

AFQ/api.py

get_nearest cannot find the customb0 file in the test that uses it, so I switched to using get instead. 
This fixes this test: https://github.com/yeatmanlab/pyAFQ/blob/71096f443fa76e98c3ecb24f6def125db67eedf6/AFQ/tests/test_api.py#L446
Which should fix one of the nightly builds.

BF: use get instead of get_nearest

---

AFQ/api.py
AFQ/data.py
AFQ/tests/test_api.py
examples/plot_afq_api.py
examples/plot_afq_callosal.py
examples/plot_afq_reco80.py
examples/plot_bids_layout.py

#494
- Review `MNI_AAL.txt`. Plot resulting callosal streamlines with aal endpoints
- [Stanford Data Repo](https://stacks.stanford.edu/file/druid:rt034xr8593/)
(See https://github.com/nrdg/cloudknot/blob/master/examples/02_process_mri_data.ipynb)

Enh Add Callosum ROIs support

---

AFQ/api.py
AFQ/mask.py
AFQ/segmentation.py
AFQ/tests/test_segmentation.py
AFQ/utils/volume.py
AFQ/viz/utils.py
examples/optic_radiations.py
examples/plot_callosal_tract_profile.py
examples/plot_tract_profile.py

This avoids strange edge cases, where the one voxel thick ROIs get squished by the SyN mapping and nothing remains of them, raising an error from `patch_up_roi`.

Dilate the ROIs.

---

AFQ/tests/test_api.py

The only nightly failing now is nightly5. It contains one test: test_AFQ_anisotropic. That test passes locally. I wonder if the new way of calculating APM uses more memory? What's weird is this test does not even do tractography. This PR makes the test do even less, which will hopefully help it pass.

Reduce apm test workload

---

AFQ/api.py
AFQ/data.py

Resolves #584 
Resolves #375 
This PR fixes a couple issues in `download_and_combine_afq_profiles`. First, since the derivatives weren't included in the `BIDSLayout`, the `layout.get()` call returned no files and there were none available to concatenate. Next, unless `out_file` was an absolute path, `out_file` in the `InTemporaryDirectory()` context did not point to the same file as the one outside of it in the `fs.put()` command. And indeed, the csv would not be saved locally in the user's current working directory, but instead in the temp directory. This PR fixes those issues and in so doing, it makes the `combine_list_of_profiles` function only return the dataframe. Saving to file is now done outside that function.

FIX: combine AFQ profiles

---

setup.cfg

Some tools have issues with various version of numpy (e.g. [cvxpy](https://github.com/cvxgrp/cvxpy/issues/1229) versions before `1.1.10` were only compiled on pypi with numpy `1.20`), which can in turn cause a bunch of install issues.
This PR proposes that we relax the numpy requirement here, using a version that was fixed for pyafq 0.6 as the lower bound, and requiring the version stay below the latest minor release, 1.20, for the time being. We also update the cvxpy requirement to get past the fixed numpy issue from their side.
I've tested this in a config locally with numpy `1.19.1` and things work as expected.

Relax versions to avoid cvxpy/numpy incompatibility

---

setup.cfg

This is a problem in the context of our hub configuration, where we need a match between the versions of `dask` and `dask-distributed`.

Allow more flexibility in dask version

---

.github/workflows/test.yml
setup.cfg

I am trying to strike a balance here between only allowing versions we know work, and not being too strict about versions.

Add conflict checker; loosen up dependencies

---

AFQ/api.py
AFQ/definitions/mapping.py
AFQ/definitions/mask.py
AFQ/definitions/scalar.py
AFQ/definitions/utils.py
setup.cfg

Allows user to describe Itk map to use instead of our generated mappings. I tested its compatibility with a map from QSIprep. The example in the docstring should be helpful.
This touches a lot of files because I fixed a few dosctrings in other definitions.

Allow ItkMap in pyAFQ

---

AFQ/api.py
AFQ/viz/fury_backend.py
AFQ/viz/plotly_backend.py

allow user to flip axial in plotly visualization from API

[FIX] Propogate flip axial to export_all

---

AFQ/api.py

I will test this on the optic bids data

[FIX] remove invalid sls from tractography, which could be custom

---

AFQ/api.py

Also, it was generating sl_counts of 0 in my experiments with it.
I think that the failure with more than one subject arises because
when one subject has that added to their row, it gets added to the columns
for the entire dataframe, but no value gets added in other rows. So,
when pandas gets to the next row it freaks out.
I suspect this is also the reason that the nightly3 tests are currently failing (?).
At any rate, I think this fix is more consistent with how we are doing
things with other files/quantities here. The only challenge is that it requires one
more read of the entire segmented tractogram from file, so that can add some time.

BF: _gen_sl_counts function was failing with more than one subject

---

AFQ/api.py

Otherwise, this function raises `KeyError: 'ROIs'` when it tries to deal with a Recobundles-formatted input in bundle_info.

BF: Set up bundle dict in cases where a dict is provided, but algo is "reco"

---

.github/workflows/docker_pyafq.yml

This is because there is no way to give PRs access to secrets.

[FIX] Build and push pyAFQ docker image only after merge

---

AFQ/api.py
AFQ/data.py
AFQ/definitions/mapping.py
AFQ/definitions/mask.py
AFQ/definitions/scalar.py
AFQ/registration.py
AFQ/segmentation.py
AFQ/tests/test_api.py
AFQ/tests/test_registration.py
AFQ/tests/test_segmentation.py
AFQ/tractography.py
AFQ/utils/volume.py
AFQ/viz/utils.py
examples/optic_radiations.py
examples/plot_callosal_tract_profile.py
examples/plot_recobundles.py
examples/plot_tract_profile.py

This PR:
1. use dipy functions instead of some of the functions we have in afq.registration . We moved afq.registration functions to dipy but have not started using the dipy functions yet. This PR gets the low hanging fruit. 
2. Give user the option to pass kwargs to slr and syn registration
3. Fixes AffMap to actually apply the correct affine
4. removes convex hull adjustment for transformed ROIs. This was dilating them.

[ENH] A variety of registration improvements, primarily for babyAFQ

---

AFQ/api.py
AFQ/definitions/mapping.py
AFQ/tests/test_api.py

One is a copy/paste typo in SLR map.
The other is that when sl counts was removed from the AFQ object data_frame, the corresponding test had to be updated.
Also a minor change in the order of export all, so that the profiles are combined right after they are generated.

[FIX] Minor BF for nightly tests

---

AFQ/tasks/viz.py
examples/plot_afq_callosal.py

When deindented this block of code can raise something like the following error, when used in the context of bundles that don't have endpoint AAL ROIs (e.g., callosal bundles):
```
File "/mnt/batch/tasks/shared/miniconda/lib/python3.8/site-packages/AFQ/api.py", line 949, in export_all
self.indiv_bundles_figures
File "/mnt/batch/tasks/shared/miniconda/lib/python3.8/site-packages/AFQ/api.py", line 899, in __getattribute__
_getter_helper(wf_dict, attr_name)
File "/mnt/batch/tasks/shared/miniconda/lib/python3.8/site-packages/AFQ/api.py", line 207, in _getter_helper
return wf_dict[attr_name]
File "/mnt/batch/tasks/shared/miniconda/lib/python3.8/site-packages/pimms/calculation.py", line 466, in __getitem__
self._run_node(self.plan.efferents[k])
File …
```

BF: Only generate warped endpoint ROIs if there are endpoint ROIs to use

---

.github/workflows/test.yml
AFQ/api.py
AFQ/segmentation.py
AFQ/tests/test_api.py
examples/plot_recobundles.py
examples/plot_tract_profile.py

This provides informative errors if no files are found inside the entire BIDS layout or in the specific derivatives folder, which would be a result of incorrect BIDS structure.
The added test adds ~5 minutes to the test because initializing api.AFQ objects takes ~1.5 minutes each.

[ENH] Provide more informative errors for incorrect BIDS structure, generate bundle dict lazily

---

AFQ/data.py

When the UW library's website is down for maintenance (as it is right now), the AAL atlas, which is stored there, becomes inaccessible, and pyAFQ raises an error when it tries to find it (but only on new installations, for example in ephemeral cloud computing resources). I am hoping that figshare is less likely to go down for maintenance without providing an alternative.

Move AAL atlas to figshare

---

AFQ/api.py

This fixes a bug introduce in the Pimms PR. The master code in api.AFQ.__getattribute__ has a bug, it iterates over every subject in valid_sub_list and then for each subject iterates over every session in valid_ses_list. The valid sub and ses lists are not constructed this way, however, because not every subject is in every session. The master code is redundant and may lead to subject/session combinations that are not valid.

BF: loop over valid_sub and valid_ses lists correctly

---

AFQ/utils/bin.py

This PR has three small changes:
1. Fixes a bug where in one part of the code, we assumed arguments ending in `_params` were special (the new `parallel_params` was being treated like `segmentation_params`, `tracking_params`, `clean_params`)
2. Allows **kwargs to have its own section in the config file ([KWARGS]) 
3. Minor flake8 changes

BF: Fix config file reader for new params

---

.github/CITATION.cff
docs/source/index.rst

This is a new format that GitHub supports: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files. I did a bit of a hack on it here, and I wonder if it will work this way. We do want people to cite our paper moving on, not the repo...

Adding a citation file.

---

AFQ/definitions/mapping.py

This breaks these mappings, and was introduced when introducing PIMMS. It would be nice to have smoke tests for these mappings, however then we would need to have fnirt/itk mappings generated for the tests.

[BF] ITK and FNIRT mappings had typo reversing reg_subject and reg_template

---

.github/workflows/docbuild.yml
.github/workflows/nightly_anisotropic_test.yml
.github/workflows/nightly_basic_test.yml
.github/workflows/nightly_custom_test.yml
.github/workflows/nightly_msmt_and_init_test.yml
.github/workflows/nightly_pft_test.yml
.github/workflows/nightly_reco_test.yml
.github/workflows/nightly_slr.yml
.github/workflows/nightly_test.yml
.github/workflows/test.yml
AFQ/api.py
docs/source/installation_guide.rst
setup.cfg

This allows installation of afq browser to be optional.

[ENH] Allow AFQ browser installation to be optional

---

AFQ/tasks/viz.py
AFQ/viz/fury_backend.py
AFQ/viz/plotly_backend.py
AFQ/viz/utils.py
examples/plot_callosal_tract_profile.py
setup.cfg

A user found these plots to be particularly helpful:
So I am trying to replicate these plots within our existing visualization framework. 
I am breaking this down into steps:

[ENH] Replicating mAFQ visualizations using our rendering framework

---

AFQ/api.py
AFQ/tests/test_api.py
setup.cfg

Fixes #767 and #763 . I think this whole system will be redesigned in #764 anyways. The problem here is that the default config file was being populated with the default params from each function's documentation, but in in the seed mask case, that default is None. We want by default to replace the `None` arguments with proper seed mask definitions in this case. If the user doesn't want to mask, they should use FullMask

[FIX] this is a quick fix for the problem with using the default config file

---

docs/source/usage/docker.rst
docs/source/usage/index.rst
pyafq_docker/Dockerfile

This makes the image more useful, for example in working with singularity.
Example usage:
```
docker run -v bids_dir:/bids_dir:rw ghcr.io/nrdg/pyafq bids_dir/config.toml
```

[ENH] Add entrypoint for pyAFQ docker image

---

setup.cfg

We were forcing an older version of cvxpy, which imported something from scipy which was just deprecated. This PR updates cvxpy.

[FIX] update cvxpy

---

AFQ/tasks/data.py
docs/source/developing/tasks.rst

This should fix the CLI, however I wonder if this should be documented somewhere

[FIX] fix CLI, % sign in scraped docstring causes error in argparser for CLI

---

AFQ/tests/test_api.py

The custom nightly keeps running out of memory. Here I tried to lighten the load on that action.

[test] Move reco80 from custom to anisotropic nightly test

---

docs/source/getting_help.rst

This is just a small change to the documentation that helps users differentiate between issues and discussions. Maybe we can spark some discussion here!

DOC: Add pointer to discussions page in getting_help.rst

---

AFQ/tests/test_api.py

This test passes locally but is causing memory errors in the nightly's

Reduce memory consumption of Reco80 test

---

AFQ/data/fetch.py
AFQ/definitions/utils.py
AFQ/tasks/decorators.py
AFQ/tasks/mapping.py
AFQ/tasks/segmentation.py
AFQ/utils/path.py
AFQ/utils/streamlines.py
AFQ/utils/tests/test_path.py

Once this is merged, we should consider a minor release as this is needed to work with QSIprep

[FIX] Replace split(.) with splitext()

---

AFQ/segmentation.py
AFQ/tests/test_api.py
AFQ/tests/test_segmentation.py
examples/plot_afq_api.py

@arokem  this PR puts the endpoint segmentation before the tie breaking, and works. I also made some changes to the API of the clean endpoints function, and I label this as WIP because I have a few ideas about rewriting the segmentation module based on how we currently use it.

FIX: Reorder endpoint

---

AFQ/tasks/data.py
AFQ/tasks/segmentation.py
AFQ/tasks/viz.py
AFQ/tests/test_api.py

These can already be calculated from our derivatives, but now they are formally added to the task system. 
Also adds a change for tract profile calculation that should significantly speed it up.

ENH: add lower triangular scalars from DTI (could be useful for ML)?

---

AFQ/definitions/mapping.py
AFQ/tasks/mapping.py

Fixes a few random things from what I have seen in NKI run. CSD APM calculated even though it is not used. b0_transform calculated even though our ITK map imported does not do subject->template transformation. Does not fix the ITK mapping problem though, as the template_xform also shows the mapping problem.

[FIX] only calc subject registration images when necessary

---

AFQ/api/group.py
AFQ/api/participant.py
AFQ/definitions/mapping.py
AFQ/tasks/data.py
AFQ/tasks/decorators.py
AFQ/tasks/mapping.py
AFQ/tasks/segmentation.py
AFQ/tasks/tractography.py
AFQ/tasks/utils.py
AFQ/tasks/viz.py
AFQ/tests/test_api.py

This PR has two parts, both affect output file names.
1. Propose a framework for easily handling pyAFQ outputs according to what they dependent. In this case, we use a depends field we put in the json files. Also, you can exclude particular outputs if you want. This is, I think, a more elegant solution to #799 and #795
2. Make pyAFQ outputs follow a more BIDS-y format. Discussed previously in #819

[ENH] Apply arbitrary command to some/all pyAFQ outputs, more BIDSy names

---

AFQ/api/bundle_dict.py
AFQ/api/group.py
AFQ/api/participant.py
AFQ/data/fetch.py
AFQ/definitions/mapping.py
AFQ/segmentation.py
AFQ/tasks/decorators.py
AFQ/tasks/mapping.py
AFQ/tasks/segmentation.py
AFQ/tasks/tractography.py
AFQ/tasks/viz.py
AFQ/tractography.py
AFQ/utils/volume.py
AFQ/viz/fury_backend.py
AFQ/viz/plot.py
AFQ/viz/plotly_backend.py
AFQ/viz/utils.py
bin/pyAFQ
examples/plot_callosal_tract_profile.py

Particularly for saving of files, so that we get more information about what is being saved and when. Output is more verbose, but that should help with #857, where not a lot of information is provided except for the prog bars.

Set logger levels to INFO

---

AFQ/_fixes.py
AFQ/segmentation.py
AFQ/tractography.py
examples/plot_afq_api.py
examples/plot_optic_radiations.py

Previously, min_length, max_length, and step_size were all in voxel space units but we docs said they were in mm.  Now, min_length and max_length are input in mm and docs clarify that step_size is in voxel space units. Then, min and max length are converted to step size units. I think this makes the most sense.

[FIX] correctly calculate min / max sl length, update step_size docs

---

AFQ/tractography.py

I am still a little confused by what the parameters input to DIPY's tractography algorithm means in terms of units. For example, a max length of 250mm causes problems for many bundles in HBN, however that should be long enough for a typical brain? This was triggered by lowering of max length from 1000mm in recent PR.

[FIX] Updating DIPY tracking params

---

AFQ/utils/bin.py
examples/plot_afq_api.py

If output_dir is set, afq_metadata.toml needs to be put there instead of derivatives/afq

[FIX] put afq_metadata.toml in the correct spot

---

.github/workflows/docbuild.yml
AFQ/utils/docs.py
docs/source/conf.py
examples/plot_viz.py

Following up on the conversation we had at our group meeting about visualizations, here is a documentation example that uses fury to visualize streamlines, core bundles with profiles (emulating Figure 1 [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0049790), but with a better colormap 😉), and surface renderings (waypoint ROIs in this case). I tried to write detailed explanations for every step here, but let me know if something is not clear. 
This example generates the following figures step-by-step:

DOC: Adds an example of visualizations using FURY.

---

AFQ/api/bundle_dict.py
AFQ/api/group.py
AFQ/api/participant.py
docs/source/usage/bundledict.rst

also adds suffix for cmd_outputs

Increase inclusion tolerance for pAF; add suffix for cmd_outputs

---

AFQ/segmentation.py
docs/source/usage/converter.rst
examples/plot_bids_layout.py

Two things here:
1. Update docs regarding name change to import_tract for importing custom tractographies
2. Only run additional bundle recognition like endpoint filtering and orientation filtering if streamlines are found in the first place

[FIX] Import tract docs

---

.github/workflows/publish-to-test-pypi.yml

Apparently "pep517" is being replace by "build".

MAINT: pep517 => build.

---

AFQ/_fixes.py
AFQ/definitions/image.py
AFQ/tasks/data.py
AFQ/tests/test_api.py
examples/plot_afq_api.py

Finding the FP in this subject with this number of streamlines has always been touchy, so I am not too worried about that.
After these fixes pass the test, we can do a minor release.

[FIX] Add max length constraint, b0 fix

---

AFQ/_fixes.py
AFQ/segmentation.py
AFQ/tests/test_fixes.py

It my case, it reduced the clean time from around 15 minutes to around 4 seconds (225x speedup).
We do this by using numpy functions instead of for loops. In _fixes for now, but can be moved to dipy later.

[ENH] Much faster mahal cleaning

---

.github/workflows/docbuild.yml
.github/workflows/test.yml
AFQ/tasks/decorators.py
AFQ/tasks/segmentation.py
AFQ/tasks/tractography.py
AFQ/tests/test_api.py
AFQ/tractography/tractography.py
AFQ/utils/streamlines.py
examples/tutorial_examples/plot_afq_api.py
setup.cfg

This supersedes #818, because the rebase became too complicated.

Incorporate TRX

---

AFQ/api/group.py
AFQ/data/fetch.py
AFQ/tests/test_api.py
examples/tutorial_examples/plot_bids_layout.py

add "GeneratedBy"s in `dataset_description.json` for BIDS 1.4+ compliance

---

AFQ/segmentation.py

It seems as though the different parallel engines occasionally cause crashes on different systems. These crashes are also hard to debug. Here I set the default segmentation to be serial, which is often what we end up doing anyways. Users can still set this to parallel if they need to speed up the segmentation step.

[FIX] set default back to serial

---

AFQ/afq_bids_entities.json
AFQ/api/group.py
AFQ/api/participant.py
AFQ/data/fetch.py
AFQ/tasks/data.py
AFQ/tasks/utils.py
AFQ/tests/test_api.py
docs/source/conf.py
examples/tutorial_examples/plot_bids_layout.py

This is an attempt to address some of the issues raised in #1013 , and to make pyAFQ outputs more bids compatible

[ENH] more specific bids entities and fixes to be bids compatible

---

AFQ/viz/plot.py

Should get rid of the following warning:
```
/Users/arokem/source/pyAFQ/AFQ/viz/plot.py:165: FutureWarning:
The `ci` parameter is deprecated. Use `errorbar=('ci', 95)` for the same effect.
```

RF: Update call to seaborn plotting.

---

AFQ/models/csd.py

Based on a recent [discussion on the dipy repo](https://github.com/dipy/dipy/discussions/3037#discussioncomment-8148381)

Use only the lowest shell in calculation of the CSD response function.

---

AFQ/segmentation.py
examples/tutorial_examples/plot_001_afq_api.py

- Endpoint ROIs filter by indexing, not cdist
- prob map and cross_streamlines calculated on the fly, in case of bundledict that does not require them

[ENH] Some segmentation speed-ups

---

setup.cfg

An earlier version of joblib causes a problem in our dockerfiles with the current version of dipy. When dipy checks if joblib was installed, it ends up in a hard lock. This does not occur on the latest version.

[FIX] force upgraded joblib

---

AFQ/viz/utils.py

Fixes https://github.com/yeatmanlab/pyAFQ/issues/1114 by correcting a bug in the viz/utils inferior fronto-occipital name, and adding some colors to use for the pARC/VOF

[FIX] fix bundle colors

---

AFQ/api/bundle_dict.py
AFQ/api/group.py
AFQ/api/participant.py
AFQ/tasks/decorators.py
AFQ/tasks/segmentation.py
AFQ/tasks/tractography.py

Closes #1098 
Also adds some small changes:
- make it more clear that you don't need to set the bids info when using participant afq
- adds more info in profiles sidecar
- makes co-located messages goto info, not warning, as they occur by default
- add info on seed/stop mask

[ENH] make source field relative in json sidecars

---

setup.cfg

It's a lightweight library and currently it is used in the examples. So, currently, a user could install pyAFQ but get an error from trying to run an example from not having altair. currently, they would have to do pip install pyAFQ[plot]

Make altair required

---

AFQ/api/bundle_dict.py
AFQ/api/group.py
AFQ/api/participant.py
AFQ/definitions/image.py
AFQ/definitions/mapping.py
AFQ/tasks/data.py
AFQ/tasks/decorators.py
AFQ/tasks/mapping.py
AFQ/tasks/segmentation.py
AFQ/tasks/tractography.py
AFQ/tasks/viz.py
AFQ/tests/test_api.py
AFQ/tests/test_definitions.py
setup.cfg

Creates a ParallelGroupAFQ class inheriting from GroupAFQ to allow for easier parallelization through pydra. Does not currently work; in progress.

Adds ParallelGroupAFQ

---

AFQ/tasks/tractography.py
AFQ/tractography/tractography.py
docs/source/reference/kwargs.rst
examples/tutorial_examples/plot_001_afq_api.py
setup.cfg

This adds a num_chunks argument to tracking_params which causes the streamlines task to generate multiple trx files in parallel using ray, and then concatenate them at the end.

Streamlines task in parallel using ray

---

AFQ/data/fetch.py

Current mapping is:
ARC include0 = SLF include0
ARC include1 = SLF exclude0
ARC include2 = SLF include1
This results in premature clipping of the ARC as ARC include2 is between ARC include0 and ARC include1.
Swapping the mapping ensures that ARC is clipped correctly by redefining the ROIs mapped from the SLF.
Before
After

[FIX] Update fetch.py with pediatric ARC ROI mapping

---

AFQ/recognition/tests/test_recognition.py
AFQ/tasks/viz.py
AFQ/tests/test_api.py
docs/source/reference/kwargs.rst
docs/source/reference/methods.rst
examples/howto_examples/baby_afq.py

I broke this parameter over a year ago it looks like. I would like to remove it though, instead of fixing it, because it's redundant. If you don't want endpoints, don't put them in your bundledict!

[FIX] Remove unused parameter, filter_by_endpoints

---

AFQ/tasks/data.py
AFQ/tests/test_api.py

Fixes the bug found in #1156 . Without the changes, the new test will throw the error:
```
IndexError: boolean index did not match indexed array along dimension 3; dimension is 160 but corresponding boolean dimension is 10
```

[FIX] Fix bug in filtering by bval, where b0 calculation used mismatched dwi and gtab
